### ISSUE TITLE
Support disconnected nodes or islands

### ISSUE THREAD

**Issue by mzy2240** [qingchen3/D-tree#2]
After reproducing the code, it seems that it does not support graph with islands or disconnected nodes. In many applications, it is very common that the nodes are constant or pseudo-constant while the edges are frequently updated. Is there a way to quickly add the support?

Attached is an example where the graph adjacency list has four nodes while the spanning tree cannot capture the disconnected node. Maybe a distributed spanning tree could be a solution?
![image](https://user-images.githubusercontent.com/18620336/207145004-b475f96e-835e-4fb8-bdc1-fdeb4173bb42.png)

**Comment by qingchen3** [comment]
In short, set n = 4. 

Long answer. Our codes support graphs that contain more than one connected components, i.e., arbitrary number of connected components and isolated vertices.

**Comment by mzy2240** [comment]
It seems not working
![image](https://user-images.githubusercontent.com/18620336/207376883-e67260b6-e9f8-4d4d-9405-355be1e0a801.png)

**Comment by qingchen3** [comment]
In constructST_adjacency_list(graph, n) function, 
    for u in range(1, n):
        if not visited[u]:
            u is isolated node.

You can add those isolated vertices in D-tree by using the line 210-211 in evaluate.py:
            if a not in Dtree:
                Dtree[a] = DTNode(a)

**Comment by mzy2240** [comment]
Thank you! It seems to work now, with a minor change: line 102 in `tree_utils.py` need to be removed.
