### ISSUE TITLE
optimal way to delete any link

### ISSUE THREAD

**Issue by mzy2240** [qingchen3/D-tree#3]
What's the most efficient way to delete any link? considering we don't know whether a link is a tree edge or not, it seems right now the best way is to check whether the link is contained in the nte list. Is that the optimal way to do?

By the way, insertion seems to be 3X slower than deletion, which is very surprisingly. Most of the time are spent on finding the root. Any idea how to improve on this?

**Comment by qingchen3** [comment]
> What's the most efficient way to delete any link? considering we don't know whether a link is a tree edge or not, it seems right now the best way is to check whether the link is contained in the nte list. Is that the optimal way to do?
> 
There are more than 2 decades of research work to solve this question. Optimal solution depends on your input graphs. 

> By the way, insertion seems to be 3X slower than deletion, which is very surprisingly. Most of the time are spent on finding the root. Any idea how to improve on this?
Does your graph have a large diameter?

**Comment by mzy2240** [comment]
Large graph (>20k vertices) with low sparsity (~0.018%). Any insight on this type of graph?

**Comment by mzy2240** [comment]
> 

I can think of ordered/sorted set/list to hold the nte, but the problem is each element is a tuple instead of a real number.
