### ISSUE TITLE
The structure has good single-thread performance but initialization/copy cost is non-neglectable

### ISSUE THREAD

**Issue by mzy2240** [qingchen3/D-tree#4]
I did a very thorough evaluation today, and I can confirm it is pretty fast at insertion, deletion, and query. However, ~~it is not thread safe~~, and not matter whether deepcopy the tree or re-construct from scratch, the time cost is unacceptable. I’m wondering if you have any idea how to use it in a real production environment.

**Comment by qingchen3** [comment]
Thanks for your comment. You are mentioning one of our future work, which is super interesting! I am not sure about your production environment. I am happy to have Zoom meeting if you want. My email is qing@ifi.uzh.ch.

**Comment by mzy2240** [comment]
email sent
